services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      DISK_SIZE: "256G"
      RAM_SIZE: "16G"
      CPU_CORES: "10"
      USERNAME: "alex"
      PASSWORD: "computer"
      REGION: "fr-FR"
      KEYBOARD: "fr-FR"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/alexandre/windows:/storage
      - /home/alexandre/windows_share:/data # Open 'File Explorer' and click on the 'Network' section, you will see a computer called host.lan. Double-click it and it will show a folder called Data, which can be bound to any folder on your host via the compose file:
    restart: always
    stop_grace_period: 2m
